WITH MAX_PRICE_PER_CATEGORY AS (
    SELECT `CATEGORY`, MAX(`PRICE`) AS MAX_PRICE
    FROM `FOOD_PRODUCT`
    WHERE `CATEGORY` IN ('과자', '국', '김치', '식용유')
    GROUP BY `CATEGORY`
)

SELECT 
    FP.`CATEGORY`,
    FP.`PRICE` AS MAX_PRICE,
    FP.`PRODUCT_NAME`
FROM `FOOD_PRODUCT` FP
JOIN MAX_PRICE_PER_CATEGORY MPPC ON FP.`CATEGORY` = MPPC.`CATEGORY` AND FP.`PRICE` = MPPC.MAX_PRICE
ORDER BY FP.`PRICE` DESC;